'use strict';
const test = require('node:test');
const assert = require('node:assert/strict');
const { assignExperimentUnit, authorizeTransition, estimateElasticity, evaluateExperiment, recommendPrice, validateExperiment, validateSnapshot } = require('../domain/pricingPolicy');
const { providerReadiness, requireProviders } = require('../services/providerBoundary');

function snapshot() {
  const sources = Object.fromEntries(['transactions','inventory','promotions','costs','competitors','demand','customer_constraints'].map((name, index) => [name, { system: `system-${name}`, version: 'v2', digest: String(index + 1).repeat(64) }]));
  return {
    tenantId: 'tenant-1', snapshotId: 'snap-1', version: 2, sku: 'sku-1', asOf: '2026-07-18T12:00:00Z', currency: 'USD', fairnessRuleVersion: 'fair-v3',
    currentPriceMinor: 1200, costMinor: 700, inventory: { onHand: 150, target: 100 }, sources,
    transactions: [{ priceMinor: 1000, units: 100, period: 'p1' }, { priceMinor: 1100, units: 90, period: 'p2' }, { priceMinor: 1200, units: 80, period: 'p3' }, { priceMinor: 1300, units: 70, period: 'p4' }],
    competitorObservations: [{ competitorId: 'c1', priceMinor: 1150, observedAt: '2026-07-18T10:00:00Z', evidenceDigest: 'a'.repeat(64) }, { competitorId: 'c2', priceMinor: 1250, observedAt: '2026-07-18T11:00:00Z', evidenceDigest: 'b'.repeat(64) }],
    promotions: [{ promotionId: 'promo-1', startsAt: '2026-07-18T00:00:00Z', endsAt: '2026-07-20T00:00:00Z', maximumPriceMinor: 1300 }],
    segments: [{ segmentId: 'retail', minimumPriceMinor: 800, maximumPriceMinor: 1500 }, { segmentId: 'loyal', minimumPriceMinor: 900, maximumPriceMinor: 1400 }],
    constraints: { marginFloorBasisPoints: 2000, maxChangeBasisPoints: 1000, competitorGuardrailBasisPoints: 2000, demandAdjustmentBasisPoints: 50 }
  };
}

function experiment() { return { experimentId: 'exp-1', sku: 'sku-1', startsAt: '2026-08-01T00:00:00Z', endsAt: '2026-08-15T00:00:00Z', recommendationDigest: 'd'.repeat(64), controlBasisPoints: 2000, treatmentBasisPoints: 8000, minimumSamplePerArm: 100, metrics: ['incremental_margin','conversion','churn','cannibalization'] }; }

test('validates all authoritative source classes and segment constraints', () => { const result = validateSnapshot(snapshot()); assert.equal(result.ok, true); assert.match(result.snapshotDigest, /^[a-f0-9]{64}$/); });
test('rejects missing provenance, malformed competitor evidence, and protected-attribute pricing', () => { const invalid = snapshot(); invalid.sources.costs.digest = ''; invalid.competitorObservations[0].priceMinor = 0; invalid.segments[0].protectedAttributes = ['race']; const result = validateSnapshot(invalid); assert.equal(result.ok, false); assert.equal(result.errors.length, 3); });
test('estimates negative elasticity and identifies sparse products', () => { const estimated = estimateElasticity(snapshot().transactions); assert.equal(estimated.status, 'estimated'); assert.ok(estimated.elasticity < 0); assert.equal(estimateElasticity(snapshot().transactions.slice(0, 2)).status, 'insufficient_data'); });
test('holds new and sparse products instead of inventing a price', () => { const sparse = snapshot(); sparse.newProduct = true; sparse.transactions = []; const result = recommendPrice(sparse, '2026-07-19T00:00:00Z'); assert.equal(result.status, 'insufficient_data'); assert.equal(result.recommendedPriceMinor, sparse.currentPriceMinor); });
test('applies margin, inventory, competitor, promotion, change, and fairness constraints explainably', () => { const result = recommendPrice(snapshot(), '2026-07-19T00:00:00Z'); assert.equal(result.status, 'review_required'); assert.equal(result.recommendedPriceMinor, 1188); assert.equal(result.onePriceAcrossSegments, true); assert.equal(result.constraintsApplied.length, 7); assert.match(result.recommendationDigest, /^[a-f0-9]{64}$/); });
test('returns an explicit conflict instead of violating a promotion or margin floor', () => { const conflicted = snapshot(); conflicted.costMinor = 1100; conflicted.constraints.marginFloorBasisPoints = 5000; const result = recommendPrice(conflicted, '2026-07-19T00:00:00Z'); assert.equal(result.status, 'constraint_conflict'); assert.equal(result.recommendedPriceMinor, null); assert.ok(result.floorMinor > result.ceilingMinor); });
test('bounds demand and inventory shocks within reviewed change and promotion limits', () => { const shocked = snapshot(); shocked.inventory.onHand = 0; shocked.constraints.demandAdjustmentBasisPoints = 1000; const result = recommendPrice(shocked, '2026-07-19T00:00:00Z'); assert.equal(result.status, 'review_required'); assert.ok(result.recommendedPriceMinor <= 1300); assert.ok(result.recommendedPriceMinor <= Math.round(shocked.currentPriceMinor * 1.1)); });
test('independent approval rejects creator self-approval', () => { const good = authorizeTransition({ current: 'review_pending', next: 'approved', actor: { role: 'pricing_approver' }, recommendation: { createdBy: 1 }, approvals: [{ actorId: 2, decision: 'approve' }] }); assert.equal(good.ok, true); const bad = authorizeTransition({ current: 'review_pending', next: 'approved', actor: { role: 'pricing_approver' }, recommendation: { createdBy: 1 }, approvals: [{ actorId: 1, decision: 'approve' }] }); assert.equal(bad.ok, false); });
test('channel synchronization and rollback require typed operator evidence', () => { assert.equal(authorizeTransition({ current: 'scheduled', next: 'sync_pending', actor: { role: 'channel_operator' }, providers: [] }).ok, false); assert.equal(authorizeTransition({ current: 'scheduled', next: 'sync_pending', actor: { role: 'channel_operator' }, providers: ['commerce'] }).ok, true); assert.equal(authorizeTransition({ current: 'monitoring', next: 'rollback_pending', actor: { role: 'channel_operator' }, rollbackEvidence: { reason: 'conversion guardrail', evidenceDigest: 'e'.repeat(64) } }).ok, true); });
test('validates controlled experiment allocation, holdout, and business metrics', () => { assert.equal(validateExperiment(experiment()).ok, true); const invalid = experiment(); invalid.controlBasisPoints = 0; invalid.metrics = ['conversion']; assert.equal(validateExperiment(invalid).ok, false); });
test('assigns experiment units deterministically without persisting raw customer identifiers', () => { const first = assignExperimentUnit(experiment(), 'customer-123'); const second = assignExperimentUnit(experiment(), 'customer-123'); assert.deepEqual(first, second); assert.match(first.unitDigest, /^[a-f0-9]{64}$/); assert.ok(['control','treatment'].includes(first.arm)); assert.equal(Object.hasOwn(first, 'unitRef'), false); });
test('waits for delayed outcomes instead of publishing synthetic experiment scores', () => { const result = evaluateExperiment(experiment(), { delayedOutcomesComplete: false }); assert.deepEqual(result.status, 'awaiting_delayed_outcomes'); assert.equal(result.decision, 'hold'); });
test('measures incremental margin, conversion, churn, and cannibalization from reconciled counters', () => { const outcomes = { delayedOutcomesComplete: true, sourceDigest: 'f'.repeat(64), control: { visitors: 100, orders: 10, revenueMinor: 20000, costMinor: 10000, churnedCustomers: 3, crossProductMarginMinor: 1000 }, treatment: { visitors: 100, orders: 12, revenueMinor: 23000, costMinor: 11000, churnedCustomers: 2, crossProductMarginMinor: 1200 } }; const result = evaluateExperiment(experiment(), outcomes); assert.equal(result.status, 'evaluated'); assert.equal(result.decision, 'eligible_for_human_approval'); assert.equal(result.metrics.incrementalMarginMinorPerVisitor, 20); assert.ok(result.metrics.conversionDelta > 0); });
test('holds experiments with sparse samples or adverse churn/cannibalization', () => { const outcomes = { delayedOutcomesComplete: true, sourceDigest: 'f'.repeat(64), control: { visitors: 50, orders: 10, revenueMinor: 1000, costMinor: 500, churnedCustomers: 1, crossProductMarginMinor: 100 }, treatment: { visitors: 50, orders: 11, revenueMinor: 1200, costMinor: 500, churnedCustomers: 4, crossProductMarginMinor: 50 } }; const result = evaluateExperiment(experiment(), outcomes); assert.equal(result.status, 'insufficient_sample'); assert.equal(result.decision, 'hold'); });
test('providers fail closed until every requested authoritative adapter is configured', () => { assert.equal(providerReadiness({}).ready, false); assert.throws(() => requireProviders(['commerce'], {}), /not ready/); const env = {}; for (const name of ['COMMERCE','POS','ERP','INVENTORY','CRM','MARKET_DATA']) { env[`${name}_PROVIDER_ENABLED`] = 'true'; env[`${name}_PROVIDER_URL`] = `https://${name.toLowerCase()}.example.invalid`; env[`${name}_PROVIDER_TOKEN`] = 'runtime'; } assert.equal(providerReadiness(env).ready, true); assert.deepEqual(requireProviders(['commerce','pos'], env).map((item) => item.name), ['commerce','pos']); });
