'use strict';
require('dotenv').config({ path: require('path').join(__dirname, '..', '.env') });
const express = require('express');
const cors = require('cors');
const helmet = require('helmet');
const rateLimit = require('express-rate-limit');
const { authenticate, jwtSecret } = require('./middleware/auth');
if (!process.env.DATABASE_URL) throw new Error('DATABASE_URL is required');
jwtSecret();
const origins = String(process.env.ALLOWED_ORIGINS || '').split(',').map((item) => item.trim()).filter(Boolean);
if (!origins.length) throw new Error('ALLOWED_ORIGINS is required');
const app = express();
app.use(helmet());
app.use(cors({ credentials: true, origin: (origin, callback) => (!origin || origins.includes(origin)) ? callback(null, true) : callback(new Error('origin not allowed')) }));
app.use(express.json({ limit: '2mb' }));
app.use('/api', rateLimit({ windowMs: 15 * 60 * 1000, max: 200, standardHeaders: true, legacyHeaders: false }));
app.get('/api/health', (_req, res) => res.json({ status: 'ok', service: 'governed-pricing-optimizer' }));
app.use('/api/auth', require('./routes/auth'));
app.use('/api/governed-pricing', require('./routes/governedPricing')(authenticate));
app.use('/api', (_req, res) => res.status(404).json({ error: 'Not found' }));
const port = Number(process.env.PORT || 3001);
app.listen(port, () => console.log(`Governed pricing API listening on ${port}`));
